# Generated by Django 3.2 on 2022-02-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_auto_20220208_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='files',
        ),
        migrations.AddField(
            model_name='note',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, to='engine.File', verbose_name='Файлы'),
        ),
    ]
