# Generated by Django 3.2 on 2022-02-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_auto_20220208_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='files',
            field=models.ManyToManyField(blank=True, to='engine.File', verbose_name='Файлы'),
        ),
    ]
