# Generated by Django 3.2 on 2022-02-08 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_alter_note_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='files',
        ),
        migrations.AddField(
            model_name='file',
            name='note',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='engine.note'),
        ),
    ]
