# Generated by Django 3.2 on 2022-02-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_auto_20220208_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='note',
        ),
        migrations.AddField(
            model_name='note',
            name='files',
            field=models.ManyToManyField(blank=True, to='engine.File', verbose_name='Файлы'),
        ),
    ]
